// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button/index.vue')['default']
    Calendar: typeof import('./src/components/Calendar/index.vue')['default']
    DropDown: typeof import('./src/components/DropDown/index.vue')['default']
    'IconQuill:chevronDown': typeof import('~icons/quill/chevron-down')['default']
    Input: typeof import('./src/components/Input/index.vue')['default']
  }
}
